In [4]:
import tensorflow as tf
path = 'NN/keras/OneSort/OneColor/DayNight/'
h5_name = 'D_14_H_19_M_29_312677param_32batch_30epoch_AUGset1_combined_1773smpl'
model = tf.keras.models.load_model(path + h5_name + '.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("/NN/tflite/OneSort/OneColor/DayNight/" + h5_name + ".tflite", "wb").write(tflite_model)

1254056

# TFmodel Test

In [48]:
import numpy as np
import tensorflow as tf

# Load the TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="converted_model.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test the model on random input data.
input_shape = input_details[0]['shape']
print(input_shape)
print(np.array([128, 128, 3]))
print(np.random.random_sample(input_shape))

input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)


max_output_index = np.argmax(output_data)
print(max_output_index)



[  1 128 128   3]
[  1 128 128   3]
[[[[0.82544317 0.79577329 0.68588343]
   [0.60112292 0.98326374 0.3976966 ]
   [0.24299201 0.53272478 0.02993952]
   ...
   [0.08168055 0.01692044 0.08637249]
   [0.82873005 0.45113888 0.46182802]
   [0.30026321 0.82419026 0.03535835]]

  [[0.26876299 0.14835052 0.33926839]
   [0.35445338 0.18402655 0.04596335]
   [0.09739663 0.33088312 0.32687717]
   ...
   [0.57909425 0.444452   0.96259088]
   [0.07729789 0.9574666  0.75547977]
   [0.78863043 0.00390137 0.67617146]]

  [[0.03678169 0.30716104 0.46262222]
   [0.22367146 0.54403505 0.89224299]
   [0.08450227 0.30364928 0.72479395]
   ...
   [0.32433091 0.0396551  0.84279524]
   [0.45235343 0.37204993 0.84495357]
   [0.40670467 0.7031939  0.01104353]]

  ...

  [[0.86628758 0.64191983 0.90233517]
   [0.29425854 0.14865658 0.14423917]
   [0.97347498 0.2046673  0.7637144 ]
   ...
   [0.52885244 0.83695012 0.4741401 ]
   [0.30655546 0.22486981 0.45232204]
   [0.3016976  0.45958795 0.48882776]]

  [[0.827

In [44]:
print(output_details[0]['shape'][1])

4
